# Kafka测试环境配置
server:
  port: 8080

spring:
  application:
    name: common-log-starter-example
  # 禁用不需要的自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
  basic:
    enable: false

# 日志Starter配置 - Kafka模式
diit:
  log:
    enabled: true
    storage:
      type: kafka  # 使用Kafka存储
      async: true  # 异步发送
      batchSize: 100
      batchInterval: 1000
    
    # Kafka配置
    kafka:
      enabled: true
      accessLogTopic: access-log
      operationLogTopic: operation-log
      bootstrapServers: localhost:9092  # 本地Kafka地址
      producer:
        acks: all
        retries: 3
        batchSize: 16384
        lingerMs: 1
        bufferMemory: 33554432
    
    # 其他存储方式禁用
    elasticsearch:
      enabled: false
    http:
      enabled: false
    database:
      enabled: false
    
    # 日志记录配置
    record:
      recordParams: true
      recordResponse: false
      recordStackTrace: true
      sensitiveFields: password,token,secret

# 日志配置
logging:
  level:
    com.diit.common.log: DEBUG
    com.diit.example: DEBUG
    org.apache.kafka: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
