# Elasticsearch测试环境配置
server:
  port: 8080

spring:
  application:
    name: common-log-starter-example
  elasticsearch:
    uris: http://localhost:9200

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
  basic:
    enable: false

# 日志Starter配置 - Elasticsearch模式
diit:
  log:
    enabled: true
    storage:
      type: elasticsearch  # 使用Elasticsearch存储
      async: true  # 异步发送
      batchSize: 100
      batchInterval: 1000
    
    # Elasticsearch配置
    elasticsearch:
      enabled: true
      hosts: localhost:9200
      indexPrefix: common-log
      connectTimeout: 5000
      readTimeout: 30000
    
    # 其他存储方式禁用
    kafka:
      enabled: false
    http:
      enabled: false
    database:
      enabled: false
    
    # 日志记录配置
    record:
      recordParams: true
      recordResponse: false
      recordStackTrace: true
      sensitiveFields: password,token,secret

# 日志配置
logging:
  level:
    com.diit.common.log: DEBUG
    com.diit.example: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"